personal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from work.sitemaps import WorkSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'work' : WorkSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('work/', include('work.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('debug', include('debug_toolbar.urls')),
    path('captcha/', include('captcha.urls')),  
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

website/urls.py
from django.urls import path
from . views import *

app_name = 'website'
urlpatterns = [
    path('', home_page, name='home'),
    path('contact', contact_page, name='contact')
]

work/urls.py
from django.urls import path
from . views import *

app_name = 'work'
urlpatterns = [
    path('', home_page, name='home'),
    path('<int:pid>/',single_page, name='single')
]

website/models.py
from django.db import models

# Create your models here.
class File(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='files/')
    def __str__(self):
        return self.name
    
class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.EmailField()
    site = models.CharField(max_length=200,null=True)
    company = models.CharField(max_length=200,null=True)
    content = models.CharField(max_length=200)
    message = models.TextField(max_length=1000)
    
    def __str__(self):
        return self.content

work/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

    
class Category(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='img/',default='img/default')
    def __str__(self):
        return self.name
    
class Post(models.Model):
    url = models.CharField(max_length=500,default='https://imanbayati.github')
    category = models.ManyToManyField(Category)
    name = models.CharField(max_length=100,null=True)
    image = models.ImageField(upload_to='img/',default='img/default.jpg')
    status = models.BooleanField(default=False)
    publish = models.DateTimeField(null=True)
    update = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-publish']
        
    def __str__(self):
        return self.name  
    
    def get_absolute_url(self):
        return reverse('work:single',kwargs={'pid':self.id}) 
     
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    email = models.EmailField()
    approved = models.BooleanField(default=False)
    message = models.TextField()
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    
    def __str__(self):
        return self.name

website/forms.py
from django.forms import ModelForm
from . models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields ='__all__'
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['site'].required = False
        self.fields['company'].required = False

work/forms.py
from django.forms import ModelForm
from . models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields =['name', 'email', 'message', 'post']

website/views.py
from django.shortcuts import render
from . models import *
from . forms import ContactForm
from django.contrib import messages
from work.models import *
# Create your views here.
def home_page(request,pid=None):
    if pid != None:
        posts = Post.objects.filter(status=1,post_id=pid)[:4]
    else:
        posts = Post.objects.filter(status=1)[:4]
    files = File.objects.all()
    context = {'posts':posts,'files':files}
    return render(request, 'website/home.html',context)

def contact_page(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
           form.save() 
           messages.add_message(request, messages.SUCCESS, 'پیام شما با موفقیت ثبت شد')
        else:
            messages.add_message(request, messages.ERROR, 'متاسفانه پیام شما دریافت نشد')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'website/contact.html',context)

work/views.py
from django.shortcuts import render,get_object_or_404
from . models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from . forms import CommentForm
from django.contrib import messages

# Create your views here.
def home_page(request,cat_name=None):
    posts = Post.objects.filter(status=1)
    categories = Category.objects.all()
    if cat_name != None:
        posts = Post.objects.filter(status=1,category__name=cat_name)

    posts = Paginator(posts,9)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1) 
    context = {'posts':posts,'categories':categories}
    return render(request, 'work/home.html',context)

def single_page(request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'پیام شما با موفقیت ثبت شد')
        else:
            messages.add_message(request, messages.ERROR, 'متاسفانه پیام شما دریافت نشد')
    form = CommentForm()
    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts,id=pid)
    comments = Comment.objects.filter(post=post.id,approved=True)
    categories = Category.objects.all()
    context = {'post':post,'form':form,'comments':comments,'categories':categories}
    return render(request, 'work/single.html',context)

templates/base.html
{% load static %}
<!doctype html>
<html dir="rtl">
<head>
<meta charset="utf-8">
<title>{{title}}</title>
<link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>

<link type="text/css" rel="stylesheet" href="{% static 'fontawesomefree/css/all.min.css' %}">

<link type="text/css" rel="stylesheet" href="{% static 'fontawesomefree/css/fontawesome.min.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'fontawesomefree/css/brands.min.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'fontawesomefree/css/solid.min.css' %}">

<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'css/hover-min.css' %}">
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
<link type="text/css" rel="stylesheet" href="{% static 'css/font.css' %}">
</head>

<body>
	<!--Start Header-->
	<header>
		<nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-menu">
  			<div class="container-fluid">
    			<a class="navbar-brand" href="{% url 'website:home' %}">
					<div class="d-flex">
						<div class="memoji align-self-center">
							<img class="img-fluid" src="{% static 'img/logo.jpg' %}" alt="me">
						</div>
						<p class="text-white mt-3" style="font-size:13px;">
							چشم انداز من، بهترین بودن است. 
						</p>
					</div>  
				</a>
    			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      				<span class="navbar-toggler-icon"></span>
    			</button>
    			<div class="collapse navbar-collapse" id="navbarSupportedContent">
     			 <ul class="navbar-nav me-auto text-center mb-2 mb-lg-0 menu">
        			<li class="nav-item">
          				<a class="nav-link active" aria-current="page" href="{% url 'website:home' %}">خانه</a>
        			</li>
       				<li class="nav-item work">
          				<a class="nav-link" aria-current="page" href="{% url 'work:home' %}">
            				نمونه کارها
          				</a>
        			</li>
      			</ul>
				<div class="d-flex justify-content-center">
				<a href="{% url 'website:contact' %}">
        			<button class="btn btn-outline-warning btn-contact-me" type="submit">تماس با من</button>
				</a>
				</div>
    			</div>
  				</div>
		</nav>
		<br>


	</header>
	<br><br><br>
	<!--End Header-->
	
	<!--Start Main-->
	{% block content %}
	{% endblock %}
	<!--End Main-->
	<!--Start Footer-->
	
	<footer>
		<small class="text-center text-white py-2 d-block">
			تمام حقوق سایت نزد اینجانب محفوظ است
		</small>
	</footer>
	<!--End Footer-->
	
	
	
	
	
	
	
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>	
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://unpkg.com/@popperjs/core@2"></script>
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<script src="{% static 'fontawesomefree/js/brands.min.js' %}"></script>
<script src="{% static 'fontawesomefree/js/fontawesome.min.js' %}"></script>
<script src="{% static 'fontawesomefree/js/solid.min.js' %}"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
	
</body>
	
</html>

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Start Main -->
  <main>
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-4">
          {% for message in messages %}
            <div class="alert {{ message.tags }} fade show alert-dismissible d-flex" role="alert">
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              <p class="mb-0 ms-4">{{ message }}</p>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>
    
    <!-- Start Form -->
    <form class="contact-form" action="{% url 'website:contact' %}"  method="post"  autocomplete="on">
    {% csrf_token %}
      <div class="container">
        <div class="row">
          <div class="col-12 col-lg-4">
            <div class="form-floating mb-4 has-validation">
              <input type="text" class="form-control bg-transparent text-white" name="name" id="name" required placeholder=" نام و نام‌خانوادگی *" />
              <label for="name"> نام و نام‌خانوادگی *</label>
            </div>
            <div class="invalid-feedback">لطفا نام و نام‌خانوادگی خود را به درستی وارد نمایید</div>
          </div>
          <div class="col-12 col-lg-4">
            <div class="form-floating mb-4">
              <input type="text" inputmode="tel" class="form-control bg-transparent text-white" name="phone" required id="phone" placeholder="شماره تماس *" />
              <label for="phone">شماره تماس *</label>
            </div>
            <div class="invalid-feedback">لطفا شماره تماس خود را به درستی وارد نمایید</div>
          </div>
          <div class="col-12 col-lg-4">
            <div class="form-floating mb-4">
              <input type="email" class="form-control bg-transparent text-white" name="email" id="email" required placeholder=" ایمیل *" />
              <label for="email"> ایمیل * </label>
            </div>
            <div class="invalid-feedback">لطف ایمیل خود را به درستی وارد نمایید</div>
          </div>
          <div class="col-12 col-lg-4">
            <div class="form-floating mb-4">
              <input type="text" inputmode="url" class="form-control bg-transparent text-white" name="site" id="site" placeholder="سایت" />
              <label for="site">سایت</label>
            </div>
            <div class="invalid-feedback">لطفا آدرس سایت خود را به درستی وارد نمایید</div>
          </div>
          <div class="col-12 col-lg-4">
            <div class="form-floating mb-4">
              <input type="text" class="form-control bg-transparent text-white" id="company" name="company" placeholder="شرکت" />
              <label for="company">شرکت</label>
            </div>
            <div class="invalid-feedback">لطفا اسم شرکت خود را به درستی وارد نمایید</div>
          </div>
          <div class="col-12 col-lg-4">
            <div class="form-floating mb-4">
              <input type="text" class="form-control bg-transparent text-white" id="content" name="content" required placeholder="موضوع *" />
              <label for="content">موضوع *</label>
            </div>
            <div class="invalid-feedback">لطفا موضوع خود را به درستی وارد نمایید</div>
          </div>
          <div class="col-12">
            <div class="form-floating mb-4">
              <textarea class="form-control bg-transparent text-white" placeholder="پیام شما *" required name="message" id="text"></textarea>
              <label for="text">پیام شما *</label>
            </div>
          </div>
          <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center mb-5">
            <div class="btn-contact mb-3">
              <button class="btn btn-outline-warning" name="submit" type="submit">ارسال پیام</button>
            </div>

            <div class="d-flex justify-content-between align-items-center bg-warning px-2 icon-contact-2">
              <a target="_blank" href="mailto: bayati.pro@gmail.com" class="text-dark me-2"><i class="fa-solid fa-envelope mt-3"></i></a>
              <a target="_blank" href="http://www.linkedin.com/in/bayatipro" class="text-dark me-2"><i class="fa-brands fa-linkedin-in mt-3"></i></a>
              <a target="_blank" href="https://www.instagram.com/bayati.pro/" class="text-dark me-2"><i class="fa-brands fa-instagram mt-3"></i></a>
              <a target="_blank" href="https://telegram.me/iman9992" class="text-dark me-2"><i class="fa-brands fa-telegram mt-3"></i></a>
              <a target="_blank" href="https://wa.me/09912311015" class="text-dark me-2"><i class="fa-brands fa-whatsapp mt-3"></i></a>
            </div>
          </div>
        </div>
      </div>
    </form>



    <!-- End Form -->
  </main>
  <!-- End Main -->
{% endblock %}

templates/website/home.html
	{% extends 'base.html' %}
	{% load static %}
    {% block content %}
	<!--Start Main-->
	<main>
		<!--Start Card Top-->
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="card card-me mt-3">
						<div class="card-body flex-column">
							<p class="text-white">
								<strong>
									سلام ؛
								</strong>
							</p>
							<small class="text-white">
								من ایمان بیاتی 21 ساله، ساکن شهر تهران و دانشجوی کارشناسی دبیری ریاضی هستم. 
								من برای طراحی سایت در حوزه‌های فرانت اند و بک اند دوره های مختلفی رو گذروندم و زبان برنامه نویسی پایتون رو یاد گرفتم و همچنان در حال یادگیری هستم و هیچ وقت از یادگیری دست بر نمیدارم.
								  اگر تمایل دارید که با من به صورت دورکاری و پاره وقت کار کنید خوشحال میشم باهم بیشتر آشنا شیم:
															</small>
							<br><br><br>
							<div class="d-flex flex-column flex-lg-row icon-contact justify-content-around align-items-center">
								<a target="_blank" href="mailto: bayati.pro@gmail.com" class="text-white btn bg-transparent border-0">
									<i class="fa-solid fa-envelope mt-3"></i>
									<small class="mt-1">bayati.pro@gmail.com</small>
								</a>
								<a target="_blank" href="https://www.instagram.com/bayati.pro/" class="text-white btn bg-transparent border-0">
									<i class="fa-brands fa-instagram mt-3"></i>
									<small class="mt-1">bayati.pro</small>
								</a>
								<a target="_blank" href="http://www.linkedin.com/in/bayatipro" class="text-white btn bg-transparent border-0">
									<i class="fa-brands fa-linkedin-in mt-3"></i>
									<small class="mt-1">linkdin.me</small>
								</a>
								<a target="_blank" href="https://telegram.me/iman9992" class="text-white btn bg-transparent border-0">
									<i class="fa-brands fa-telegram mt-3"></i>
									<small class="mt-1">telegram.me</small>
								</a>
								<a target="_blank" href="https://wa.me/+989912311015" class="text-white btn bg-transparent border-0">
									<i class="fa-brands fa-whatsapp mt-3"></i>
									<small class="mt-1">whatsapp.me</small>
								</a>
								<a target="_blank" href="tel:+989912311015" class="text-white btn bg-transparent border-0">
									<i class="fa-solid fa-mobile-button mt-3"></i>
									<small class="mt-1">09912311015</small>
								</a>
							</div>
							<br><br>
							{% for file in files %}
							<a href="{{file.file.url}}" class="bg-transparent justify-content-center btn-download-file">
								<button class="btn btn-warning border-0 d-flex me-auto" type="submit">
									<i class="fa-solid fa-file-arrow-down mt-3"></i>
									<small class="mt-1 ms-1">دانلود رزومه</small>
								</button>
							</a>
							{% endfor %}
							<br>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<!--End Card Top-->
		
		
		<!--Start Work-->
		
		<div class="container">
			<p class="text-white text-center text-lg-start text-work headline mb-4">
				<strong>نمونه کارهای من</strong>
			</p>
		</div>
		<div class="bg-work mb-3">
			<div class="container">
				<div class="row">
					<div class="slider-1st">
					<div class="slider22 d-flex flex-column flex-lg-row justify-content-between">
					{% for post in posts %}
						<div class="card border-0 card-work me-3 mt-5 mb-5">
							<div class="card-img-top">
								<img class="img-fluid d-block mx-auto w-100" src="{{post.image.url}}" alt="picture">
							</div>
							<div class="card-body p-0 py-2">
								<div class="button-text d-flex justify-content-between">
									<div class="d-flex mt-2">
										<small class="text-white"> قالب :</small>
										{% for cat in post.category.all %}
										<small class="text-white ms-2">{{cat.name}}</small>
										{% endfor %}
									</div>
									<div class="btn-contact">
									<a href="{% url 'work:single' pid=post.id %}" class="btn btn-warning d-flex">
										<i class="fa-solid fa-eye mt-1"></i>
										<small class="ms-2 d-inline-block">مشاهده </small>
									</a>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>				
				</div>
				<a href = "{% url 'work:home' %}" >
				<div class="pb-4 see-more-btn">
					<button class="btn btn-outline-warning d-flex hvr-shrink" type="button">
						<i class="fa-solid fa-eye mt-1"></i>
						<p class="mb-0 ms-1">مشاهده کارها</p>
					</button>
				</div>
				</a>
			</div>
		</div>
		<br><br><br><br>
		<!--End Work-->
		
		
		<!--Start Skills-->
		<div class="container">
			<p class="text-white text-center text-lg-start text-work headline mb-4">
				<strong>مهارت ها</strong>
			</p>
			<div class="row">
				<div class="col-12 col-lg-4">
					<div class="card border-0 card-skil">
						<div class="card-body">
							<div class="icon-skill mb-3 text-center text-white">
								<i class="fa-brands fa-python"></i>
							</div>
							<p class="text-justify text-white text-center">
								برای برنامه نویسی بک اند سایت از زبان برنامه نویسی پایتون و فریمورک قدرتمند پایتون به نام django استفاده می‌کنم.
							</p>
						</div>
					</div>
				</div>
				<div class="col-12 col-lg-4">
					<div class="card border-0 card-skil my-3 my-lg-0">
						<div class="card-body">
							<div class="icon-skill mb-3 text-center text-white">
								<i class="fa-brands fa-bootstrap"></i>
							</div>
							<p class="text-justify text-white text-center">
								در کنار html و css از کتابخونه قدرتمند css به نام bootstrap استفاده می‌کنم.
							</p>
						</div>
					</div>
				</div>
				<div class="col-12 col-lg-4">
					<div class="card border-0 card-skil">
						<div class="card-body">
							<div class="icon-skill mb-3 text-center text-white">
								<i class="fa-solid fa-palette"></i>
							</div>
							<p class="text-justify text-white text-center">
								  اوایل برای طراحی سایت با برنامه adobe photoshop کار می‌کردم ولی الآن از برنامه adobe xd استفاده می‌کنم. 
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br><br>
		<!--End Skills-->
		
		
	</main>
	<!--End Main-->
    {% endblock %}

templates/work/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Start Main -->
  <main>
    <!-- Start Posts -->
    <div class="container">
      <div class="row">
        {% for post in posts %}
          <div class="col-12 col-lg-4">
						<div class="card border-0 card-work-2">
							<div class="card-img-top">
								<img class="img-fluid d-block mx-auto w-100" src="{{post.image.url}}" alt="picture">
							</div>
							<div class="card-body">
								<div class="button-text d-flex justify-content-between">
									<div class="d-flex mt-2">
										<small class="text-white"> قالب :</small>
										{% for cat in post.category.all %}
										<small class="text-white ms-2">{{cat.name}}</small>
										{% endfor %}
									</div>
									<div class="btn-contact">
									<a href="{% url 'work:single' pid=post.id %}" class="btn btn-warning">
										<i class="fa fa-eye"></i>
										<p class="mb-0 ms-2 d-inline-block">مشاهده </p>
									</a>
									</div>
								</div>
							</div>
						</div>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="page">
            <ul class="pagination justify-content-center">
              {% if posts.has_previous %}
              <li class="page-item me-2">
                <a class="page-link" href="?page={{posts.previous_page_number}}" aria-label="previous">
                  <i aria-hidden="true" class="fa fa-chevron-right"></i>
                </a>
              </li>
              {% endif %}
              {% for page in posts.paginator.page_range %}
                {% if posts.number == page %}
                <li class="page-item me-2 active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                {% else %}
                <li class="page-item me-2"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                {% endif %}
              {% endfor %}
              {% if posts.has_next %}
              <li class="page-item me-2">
                <a class="page-link" href="?page={{posts.next_page_number}}" aria-label="next">
                  <i aria-hidden="true" class="fa fa-chevron-left"></i>
                </a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <br><br>
    <!-- End Posts -->
  </main>
  <!-- End Main -->
{% endblock %}

templates/work/single.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
{% load humanize %}

<!--Start Main-->
	<main>
		
		<!--Start Post-->
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-4">
				  {% for message in messages %}
					<div class="alert {{ message.tags }} fade show alert-dismissible d-flex" role="alert">
					  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					  <p class="mb-0 ms-4">{{ message }}</p>
					</div>
					{% endfor %}
				</div>
			</div>

			<div class="row">
				<div class="col-12 col-lg-6">
						<div class="card border-0 card-work-single mb-3">
							<div class="card-img-top">
								<img class="img-fluid d-block mx-auto w-100" src="{{post.image.url}}" alt="picture">
							</div>
						</div>
						{% for cat in post.category.all %}
						{% if cat.name == 'html'  %}
						<small class="text-white mb-3 d-block">* لطفا برای مشاهده فیلترشکن خود را روشن کنید</small>
						{% endif %}
						{% endfor %}
						<div class="btn-contact d-flex mb-5 mb-lg-0 justify-content-center justify-content-lg-start">
							<a target="_blank" href="{{post.url}}" class="btn btn-success text-white">
								<i class="fa-solid fa-laptop"></i>
								<p class="mb-0 ms-1 d-inline-block">مشاهده آنلاین</p>
							</a>
						</div>
					</div>

					
				<!--Start Form-->
				<div class="col-12 col-lg-6">
					<form class="contact-form" action="{% url 'work:single' pid=post.id %}"  method="post"  autocomplete="on">
						{% csrf_token %}
						<div class="container">
							<div class="row">
								<div class="col-12 col-lg-6">
									<input value="{{post.id}}" type="hidden" name="post">
  									<div class="form-floating mb-4">
    									<input type="text" name="name" class="form-control bg-transparent text-white" required id="name" placeholder="نام و نام‌خانوادگی">
   								 		<label for="name">نام و نام‌خانوادگی</label>
  									</div>
								</div>
								<div class="col-12 col-lg-6">
  									<div class="form-floating mb-4">
    									<input type="email" name="email" class="form-control bg-transparent text-white" required id="email" placeholder="ایمیل">
   								 		<label for="email">ایمیل</label>
									</div>
								</div>
								<div class="col-12">
									<div class="form-floating mb-4">
  										<textarea name="message" class="form-control message-form bg-transparent text-white" required placeholder="پیام شما" id="text"></textarea>
  										<label for="text">پیام شما</label>
									</div>
								</div>
								<div class="btn-contact mb-3">
									<button class="btn btn-outline-warning" name="submit" type="submit">ارسال پیام</button>
								</div>
							</div>
						</div>
					</form>
				</div>
				<!--End Form-->
				
			
			</div>
		</div>
		
		<br><br><br>
		<!--End Post-->
		
		<!--Start Comments-->
		<div class="container">
				<div class="slider-2st">
					<p class="text-white text-center text-lg-start mb-4" style="font-size:18px;"><strong>نظرات</strong></p>
					<div class="slider33">
						{% for comment in comments %}
						<div class="card border-0 card-comment mx-3">
							<div class="card-body">
								<div class="d-flex">
									<p class="text-white d-inline-block">{{comment.name}}</p>
									<small class="mt-1 ms-2">{{comment.create|naturalday}}</small>
								</div>
								<p class="text-white text-start mb-0 mt-2">
									{{comment.message}}
								</p>
							</div>
						</div>
						{% empty %}
    						<small class="d-block text-white text-center">هیچ پیامی ثبت نشده</small>
						{% endfor %}
				</div>
				</div>
		</div>
		
		<!--End Comments-->

		
		
	</main>
	<br>
	<br>
	<!--End Main-->
{% endblock %}